### ISSUE TITLE
fabric.mod.json version isnt being updated

### ISSUE THREAD

**Issue by Linguardium** [JSJBDEV/PlatosTransporters#1]
for some reason each release shows 1.0.0 in the file. perhaps it would be good to use a variable to set this.

**Comment by JSJBDEV** [comment]
is there a specifically automatic way of doing this or should I just be doing it manually each update?

**Comment by Linguardium** [comment]
I use 

```
  "version": "${version}",
```

in my file and update that in the gradle.properties file

**Comment by JSJBDEV** [comment]
I also have that

**Comment by JSJBDEV** [comment]
I think its because it relies on gradle.properties
