### ISSUE TITLE
Vehicule invisible when I assemble it

### ISSUE THREAD

**Issue by Boract** [JSJBDEV/PlatosTransporters#10]
Hello, when i put the blocks and after the controller, then I right click on the controller. Just after that, the vehicule become invisible and my character is stuck in sens of I can't place any block or I can't breack anything and the only way to solve it is to reload the world or disconnect reconnect.
Thanks for reading !

**Comment by JSJBDEV** [comment]
hm... sounds like client/server desynching issues. Are you playing singleplayer or multiplayer and what version of the game and of the mod arer you on?

**Comment by Sethyboi1** [comment]
i have the same problem

**Comment by Sethyboi1** [comment]
it seems when i remove alll mods but platos it works, but i have like 50 mods so im to lazy to see which one is the culprit

**Comment by JSJBDEV** [comment]
I have actually seen this now in all forge versions and am yet to find a way of fixing it, it appears they are not invisible but rather the client doesnt recognise it as an entity, but if you leave and rejoin it suddenly appears

**Comment by JSJBDEV** [comment]
This appears to be fixed in new versions
