### ISSUE TITLE
1.15.2 Forge Server Shutdown

### ISSUE THREAD

**Issue by Jergeric** [JSJBDEV/PlatosTransporters#11]
I just had your mod run on our test server, yes the hitboxes are really too small xD

But apart from that, the server shuts down as soon as you use the key from your seat (aircraft)

[crash-2020-08-11_05.20.34-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5054624/crash-2020-08-11_05.20.34-server.txt)

**Comment by JSJBDEV** [comment]
Huh. That is a strange error. Your probably using a new forge version then me if it's a nosuchmethod problem, will have a look at it, also yeah once I work out how to dynamically scale hitboxes I'll fix that xD

**Comment by JSJBDEV** [comment]
you are using a buggy version of forge 31.2.36 platos transporters targets 31.2.0 i will look at updating this as Im going to assume that that was either forced upon you or required for some mod

**Comment by JSJBDEV** [comment]
nope this was entirely my problem, I was using a method that was apparently only client side, fixed in version 1,2,2 on CF in a few minutes
