### ISSUE TITLE
Server Shutdown [Fabric 1.16.1]

### ISSUE THREAD

**Issue by lonelydriver51** [JSJBDEV/PlatosTransporters#13]
The server is shutting down while press RMB on vehicle controller with bare hands.
[crash-2020-08-18_18.14.26-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5091390/crash-2020-08-18_18.14.26-server.txt)
[crash-2020-08-18_18.07.08-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5091392/crash-2020-08-18_18.07.08-server.txt)

**Comment by JSJBDEV** [comment]
I'll have a look at this when I can, it's most likely a similar but not exactly the same error

**Comment by JSJBDEV** [comment]
I think ive fixed it but im not sure if that might just be a java version problem, ive found an alternative anyway

**Comment by lonelydriver51** [comment]
It works, thanks a lot!

**Comment by lonelydriver51** [comment]
[crash-2020-08-20_19.06.11-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5104157/crash-2020-08-20_19.06.11-server.txt)
Woops
That happened when I surrounded my big ship with air balloons then pressed RMB on the controller. With the small structures it worked well, but not with the many-blocks things, i guess

**Comment by lonelydriver51** [comment]
[crash-2020-08-20_19.12.59-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5104176/crash-2020-08-20_19.12.59-server.txt)
No matter what engine is it, now I used the boat engine and that happened again. I think the issues is in the too many blocks in the structure.

**Comment by lonelydriver51** [comment]
[crash-2020-08-20_19.17.48-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5104209/crash-2020-08-20_19.17.48-server.txt)
That happened when I pressed RMB on the "vehicle" while the other player was in it. The server was shutted down immidiately, not like the usual crashes was.

**Comment by lonelydriver51** [comment]
[crash-2020-08-18_17.32.38-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5104252/crash-2020-08-18_17.32.38-server.txt)
![unknown](https://user-images.githubusercontent.com/69860313/90799135-40982380-e32c-11ea-8d29-e0f4d8266471.png)
Now I made the structure out of 12 fur blocks, placed air balloons on all the perimeter and the controller on the top. It crashed like usual.

**Comment by JSJBDEV** [comment]
The ships do not properly support multiple players, please open a different issues for that

**Comment by JSJBDEV** [comment]
The issue that persists for you appears to be to do with s code side thing called streams, I'm not entirely sure why this hasn't been brought up before

**Comment by JSJBDEV** [comment]
In the last error you sent you appear to be using version 1.4.2 which is not the latest can you check this again please?

**Comment by lonelydriver51** [comment]
I really don't know why it wrote 1.4.2 in the last log, we didn't even touch the mods folder, and all the previous logs shown up 1.4.3 version that was true, I'll check it again when server host will be online

**Comment by JSJBDEV** [comment]
please make a new issue if this still persists in modern versions
