### ISSUE TITLE
[Forge 1.15.2] Boats uncontrollable

### ISSUE THREAD

**Issue by Jergeric** [JSJBDEV/PlatosTransporters#14]
Aloha again,
the airships are now working 1a and are really fun, but still the boats are crazy.

When you use a boat, it always goes forward, even if you leave it, it always goes straight on xD
Unfortunately, you can then also no longer sit on it and it is also not possible to take it apart

Forge - 31.2.36
Mod - 1.2.4

**Comment by JSJBDEV** [comment]
fixed in new versions
