### ISSUE TITLE
Boat disappear after assembling

### ISSUE THREAD

**Issue by emanuele246gi** [JSJBDEV/PlatosTransporters#15]
When I create the boat it disappear, but still does exist.
I try to exit and re-enter the world and I'm on board without doing anything, and the boat keeps going without pressing any button, I have a clip that I registered today while I was trying the mod :(

**Comment by JSJBDEV** [comment]
What game version, mod version, and mod loader are you using?

**Comment by emanuele246gi** [comment]
Minecraft 1.15.2, Version 1.2.5 and latest version of Forge

**Comment by JSJBDEV** [comment]
So the wierd thing is that this doesn't appear to happen to everyone and I'm not sure what the problem is, are you using optifine or other graphics/lighting performance mods?

**Comment by emanuele246gi** [comment]
Optifine, yes

**Comment by JSJBDEV** [comment]
please could you try your setup again without optifine, it is known to cause a lot of bugs in newer versions of mc

**Comment by emanuele246gi** [comment]
Yep I saw that with other mods, if only OF developers finished 1.15.2 before 1.16 -_-

**Comment by emanuele246gi** [comment]
Ok well, the boat doesn't disappear anymore, but there are still a lot of problems that I will say in another post :/
