### ISSUE TITLE
im having an issue where it tells me i dont have enough balloon blocks when i have way more than enough. (82/148)

### ISSUE THREAD

**Issue by BlueFurr** [JSJBDEV/PlatosTransporters#16]
![2020-08-26_21 40 15](https://user-images.githubusercontent.com/70290994/91378127-518ddc80-e7e5-11ea-858f-f99ef455ff0b.png)

**Comment by JSJBDEV** [comment]
You do not have enough, you need double the amount of balloons as each balloon only provides 2 balance in this update and includes themselves

**Comment by JSJBDEV** [comment]
This is something that's being addressed for 1.5 fabric and it's forge equivalents, but for now you need a fair few more

**Comment by JSJBDEV** [comment]
I should probably point out this is somewhat of a bug, since in the screenshot you have 74 balloons which means theoretically you can only have 74 other blocks

**Comment by JSJBDEV** [comment]
I calculate 82 other blocks on your vehicle so you could lift it with 82 balloons theoretically
