### ISSUE TITLE
List of issues I have encountered

### ISSUE THREAD

**Issue by emanuele246gi** [JSJBDEV/PlatosTransporters#17]
First of all, I got a rendering issue which the boat disappears and reappears everytime I move my visual, this bring me to another issue: I can't go aboard, so this makes me not being able to use neither the ship lift jack or the disassembly wrench.

Aaaaaand the ship keeps moving alone, without my intervention

Also, little feature: can you make the boat walkable? :(

**Comment by JSJBDEV** [comment]
there have been a few people experiencing the problem of not being able to get on the ship, have you tried without optifine?

**Comment by emanuele246gi** [comment]
Yep I'm without Optifine

**Comment by emanuele246gi** [comment]
I could find the right hitbox where to click to go aboard by pressing f3 + b, and the hitbox was underwater, far from the actual controller

**Comment by JSJBDEV** [comment]
this might be a desynching issue, it may be fixed in newer versions if you want to test that, the boats shouldnt move unless the key is held now

**Comment by JSJBDEV** [comment]
also in the new versions you can use boarding stairs to get on ships, this means you should be able tog et on them from a distance even if the hitbox is a bit skewed

**Comment by emanuele246gi** [comment]
Oh thank you for both

**Comment by emanuele246gi** [comment]
Anyway, what about that last thing I asked? That would revolutionize your mod very much! :D

**Comment by JSJBDEV** [comment]
boat is unlikely to be walkable as the mod is not cut out from it, It may still be considered in the future, everything else should be fixed now :D
