### ISSUE TITLE
How exactly do i make an airship?

### ISSUE THREAD

**Issue by Sethyboi1** [JSJBDEV/PlatosTransporters#23]
i made an airship and constructing it but i a can do is turn. i can move up or down or any other direction. im holding the key (1.15.2) no mods but this one

**Comment by JSJBDEV** [comment]
to operate the airship you must right click the key to travel in the direction you are facing, more familiar controls exist in version 1.6 but I havent had time to port it to the other 3 version of minecraft I support yet
