### ISSUE TITLE
Is it based around riding a pig? 

### ISSUE THREAD

**Issue by AntiAlles** [JSJBDEV/PlatosTransporters#25]
I just traveled 12000 Blocks with the boat and when i arrived at my destination i got hit by a Lightning Bolt which turned the boat into a Zombie Pigmen and despawned all of the blocks i used for the boat.

**Comment by JSJBDEV** [comment]
Oh wow that is a fairly unique problem, yes it's based around a pig and I failed to consider that as a problem that might occur due to its unlikelyness, all I can really say is give yourself your stuff back and I will try and fix it when I next can

**Comment by JSJBDEV** [comment]
fixed in 1.6.2 for fabric won't close this just yet as it is not on forge

**Comment by AntiAlles** [comment]
Sounds great! Imma wait for the forge release

**Comment by JSJBDEV** [comment]
sorry this took way too long, I havent been deving for a while, it is fixed now 👍
