### ISSUE TITLE
Vehicles aren't drivable

### ISSUE THREAD

**Issue by Ramsji** [JSJBDEV/PlatosTransporters#26]
When creating a vehicle (car and boat) with all the steps (Ship Controller Assembly, adding enough Wheels/Water Floats and holding the Control Key) it does not move properly. 
Rotation and very slow movement is possible, but the vehicles stay on the same block height, eg. don't move up a block when driving against an edge and don't fall down when assembled and just float at the same height they're created.

I use the 'platos-transporters-1.16-1.6.1.jar' on 1.16.3 Fabric.

So am I missing something or is it a bug? ^^' 
The idea of this mod is just awesome and i'd love to be able to properly use it.

**Comment by JSJBDEV** [comment]
Hm.. you could try using the wasd keys but you should travel in a straight line with the key held, also try clicking it, otherwise I need to change some things, I'm fairly sure the airship works as intended however

**Comment by Ramsji** [comment]
The wasd keys didn't seem to have an effect on the vehicles unfortunately.
So is it intentional that the vehicles, at least those for land and water, aren't affected by gravity? (If it's intentional, negative values for the Ship Lift Jack would be neat, since assembling and disassembling let's the structure move up a block)
And yes, airships do work for me ^^

**Comment by JSJBDEV** [comment]
Ah. Yeah that's be the problem, all vehicles except the airship are suppose to be affected by gravity, put an anvil on the ship/car and it should work as intended

**Comment by Ramsji** [comment]
It works now, thanks so much! :)
