### ISSUE TITLE
No server mod?

### ISSUE THREAD

**Issue by soundeffects** [JSJBDEV/PlatosTransporters#28]
On the latest version of platos (1.6.2) for the latest version of fabric (0.10.6+build.214) for Minecraft 1.16.1, I get a fatal startup error for trying to run the mod in a server environment.

<img width="1059" alt="Screen Shot 2020-11-05 at 13 07 22" src="https://user-images.githubusercontent.com/6353447/98291143-e3ddf980-1f67-11eb-8417-e3d918baa361.png">

I'm just a little confused because earlier versions supported server environments, is that no longer true?

**Comment by JSJBDEV** [comment]
I thought I fixed this but apparently not, will try and get it done soon, I'm pretty sure I know what this error is

**Comment by JSJBDEV** [comment]
#30
