### ISSUE TITLE
issue loading 1.16.4 version

### ISSUE THREAD

**Issue by CanBoy67** [JSJBDEV/PlatosTransporters#29]
I've come across an issue whilst loading the 1.16.4 test version java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods. [here](https://pastebin.com/SqWRVk3x). I'm not sure if this is a me issue, a forge issue, or a mod issue, please take a look.

**Comment by JSJBDEV** [comment]
oh boy, that means the finally deprecated that registry, as you may know this mod was orignally for fabric and as such most of the registering is done to fabric standards, by the looks of it they have finally removed the ability to do it that way, I can tell you that this does work on 1.16.3 (as that is the version it was built for). either way, Ill update it to work properly in 1.16.4 asap

**Comment by CanBoy67** [comment]
That would be good thank you
