### ISSUE TITLE
random item pickup

### ISSUE THREAD

**Issue by RennocSrednalf** [JSJBDEV/PlatosTransporters#3]
after creating a ship some random surroundings tend to get added to the build list that are not supposed to be. I don't know the best way to go around this except maybe a wand that allows you to see/select blocks you want to tie to the ship.
![Capture - Copy](https://user-images.githubusercontent.com/67771926/86521253-42f5fb00-be1c-11ea-8724-b66fef58bb0a.PNG)

**Comment by JSJBDEV** [comment]
I'm sorry this took so long to reply, I shall add these things to the blacklist, however I'm not sure about the blocks from other mods so you may have to build your ship elsewhere, however I will try

**Comment by JSJBDEV** [comment]
so I checked and I cant put mod blocks in my blacklist by default so itd have to be a seperate datapack, dead bushes are now on the blacklist however

**Comment by RennocSrednalf** [comment]
no problem, its just wired that there's no way to determine what the ship tries to grab and not grab
