### ISSUE TITLE
A Couple Issues

### ISSUE THREAD

**Issue by CanBoy67** [JSJBDEV/PlatosTransporters#35]
I'm having a couple issues with 1.16-1.6.4 version the first issue is the vehicle is sunk into the ground and I'm unable to disassemble it and the second issue is I'm having a crash problem [here](https://pastebin.com/b00dVAsZ) is the crashlog any help would be appreciated
EDIT: Figured out first issue but discovered another issue, now I'm not sure if this is a compact machines bug or not but after I disassemble vehicle I discovered that the machine data was unloaded or removed now again this may be a compact machines issue but could you check it out

**Comment by JSJBDEV** [comment]
Theoretically machine data should be saved, although I'm not 100% guaranteeing that

**Comment by JSJBDEV** [comment]
Also that crashlog looks like it might be to do with "contraptions" I haven't got much experience with mods on forge anymore but have s check there

**Comment by CanBoy67** [comment]
It's not a big deal I seem to be able to avoid the crash if I don't get too stuck in blocks as that's when it happens, the crash may have something to do with the create mod but again it's not that big of a deal

**Comment by JSJBDEV** [comment]
i think this is to do with create, if you can find an issue without using create, please reopen the issue
