### ISSUE TITLE
Fall damage

### ISSUE THREAD

**Issue by ConnorBe05** [JSJBDEV/PlatosTransporters#40]
When you are in an air ship and touch the floor you take a massive amount of fall damage even if you descend to the ground slowly. This needs to be fixed as you can not really land the ships

**Comment by JSJBDEV** [comment]
are you riding the ship, as in sitting on it?

**Comment by JSJBDEV** [comment]
oh I think I get the error now, I thought I fixed that ages ago. I guess not

**Comment by JSJBDEV** [comment]
fixed this I think, reopen this issue if not
