### ISSUE TITLE
Smooth Quarts Stairs and Half-Slabs sometimes left behind after first dissassembly and reassembly

### ISSUE THREAD

**Issue by Pfahli** [JSJBDEV/PlatosTransporters#41]
**Serverversion:** 1.16.4 - 35.1.37

**Platosversion:** 1.4.7 (But could also be reproduced in every older version I tried (up to 1.4.3)

**Other Plugins installed:** DynmapForge + Worldedit

I found an interesting small issue with stairs and half-slabs (and thin glass-sheets). I noticed it when building a small yacht out of smooth quartz. The ship assembles perfectly as a whole unit on the first time when boarding it, but when I dissassemble it with the wrench and reassamble it, it sometimes leaves stairs and slabs behind, causing floating bricks on a boat that are held together by the invisible structure from before ("leftovers" on the left side and working "skeleton" on the right side):
![platos4](https://user-images.githubusercontent.com/8457377/109857600-26d08500-7c5b-11eb-90ce-38f7b2896c5c.JPG)

I tried to reproduce it with wooden stairs and slabs and it worked without any issues.
_Edit: I was able to reproduce it with wood as well, so it seems independent from the material_

I could reproduce it by building a seemingly random structure of stairs and slabs and noticed that it doesn't happen when the stairs are connected to a normal cube with their long side.
![platos2](https://user-images.githubusercontent.com/8457377/109857963-8890ef00-7c5b-11eb-8727-b1fcb74634dc.JPG)
![platos3](https://user-images.githubusercontent.com/8457377/109857959-87f85880-7c5b-11eb-8fee-72ef3de932ae.JPG)

**Comment by JSJBDEV** [comment]
yeah so I do actually know what this error is and I fixed it in my side port of platos thats for 1.15 called Frankys ships which will be an addon to the MineMineNoMi, I havent merged the change to the main mod because I forgot but will do it now

**Comment by JSJBDEV** [comment]
when 1.4.8 is verified please test it, it should fix your issue

**Comment by Pfahli** [comment]
Thats awesome, I will test it tomorrow and provide feedback asap!

**Comment by Pfahli** [comment]
I just tried it out again. 

Now I'm having the issue that the Game keeps crashing client-side when using the key on vehicles that would have previously caused the bug mentioned above. 
The other vehicles as well as new ones that are more robustly built still work perfectly fine.
The server keeps on running fine as well. I prefer the state right now because it won't cause the vehicle to be destroyed as previously and I can improve the vehicle on flawed spots after restarting the game.

![platos6](https://user-images.githubusercontent.com/8457377/110037651-ffeb7f00-7d3e-11eb-9bd3-676bcdb3071e.JPG)

**Comment by JSJBDEV** [comment]
this is fixed in fabric now I believe

**Comment by JSJBDEV** [comment]
This should now be fully supported in forge and fabric
