### ISSUE TITLE
1.16.5 crash

### ISSUE THREAD

**Issue by thereddduke** [JSJBDEV/PlatosTransporters#46]
Im testing out a modpack and it crashes frequently as I test Plato's transporters. I'll leave here the crash log and the modlist. Thank you in advance for you're help

**Modlist:**

Collective
MineColonies
Structurize
When Dungeons Arise
AppleSkin
Aquaculture 2
AstikorCarts [Horse Carts]
Biomes O' Plenty
Bookshelf
Botania
Carry On
Chisels & Bits
Citadel
CodeChicken Lib 1.8.+
Create
Curios API (Forge)
Dungeons Mobs
Dynamic Surroundings
Ender Storage 1.8.+
Epic Fight Mod
Hwyla
Ice and Fire: Dragons
Just Enough Items (JEI)
Mahou Tsukai
Patchouli
Plato's Transporters [FORGE/FABRIC]
Small Ships
Spartan Shields
Spartan Weaponry
Tough As Nails
Valhelsia Structures
Village Spawn Point 
Waystones
Wyrmroost
 
**Crash log:**

https://mega.nz/file/JrQlSAxJ#ZlN-nOzKZBE_qYBnuhcgYJdlI6g_ToE7DR90GXDIZgc

**Comment by JSJBDEV** [comment]
Are you sure you mean crashing? I'm not seeing anything in that log besides that you need to upgrade your Java and you haven't got enough floats/balloons/wheels etc?

**Comment by JSJBDEV** [comment]
I think I've fixed this now could you check?

**Comment by JSJBDEV** [comment]
#51
