### ISSUE TITLE
Server crash upon assembly

### ISSUE THREAD

**Issue by OreosAreNeat** [JSJBDEV/PlatosTransporters#47]
So whenever I create a vehicle, I attempt to assemble it and right-click on the ship controller assembly but when I do the entire server crashes. This was the latest version of the mod for Fabric. If any additional details are needed please let me know.

**Comment by JSJBDEV** [comment]
Crash log please

**Comment by JSJBDEV** [comment]
I just assembled a ship on a server to see if it was anything obvious but it works fine, so I will need your crash log

**Comment by JSJBDEV** [comment]
#46
