### ISSUE TITLE
File platos-transporters-1.16-1.3.1.1.jar is a Fabric mod and cannot be loaded

### ISSUE THREAD

**Issue by Akirie** [JSJBDEV/PlatosTransporters#6]
I have no idea what the problem is can you please help

**Comment by JSJBDEV** [comment]
what about it can't be loaded, do you get a crash or anything?

**Comment by Akirie** [comment]
it doesn't load from the very start when i start up forge, when it loads all my mods (currently have no others running with it) all it does is say it failed to load, the tittle of the issue was actually the error code it sent

**Comment by Akirie** [comment]
As soon as I start up forge it just tells me that it won’t load saying that
it’s a fabric mod

**Comment by Akirie** [comment]
I can play the game just fine it just Doesn’t actually include the mod when
I play

**Comment by JSJBDEV** [comment]
Plato's transporters does not work directly on forge, it is a mod for the Fabric modding toolchain which is completely seperate to forge you can find more information here https://fabricmc.net/ or you can play the Textiles Continuum modpack if you are unsure. I am currently in the process of porting this mod to forge (see the top of the CF page)
