### ISSUE TITLE
Cannot create ship [Forge 1.16]

### ISSUE THREAD

**Issue by MattiT555** [JSJBDEV/PlatosTransporters#8]
After making a small ship out of ship controller assembly, wooden planks and water floats [I made sure there are more then enough of them], right-clicking on ship controller assembly with an empty hand does nothing.

**Comment by MattiT555** [comment]
BTW: I tried many different ships, different airships and different cars, different worlds, gamemodes, shift-clicking and literally nothing seems to work.

**Comment by JSJBDEV** [comment]
hm.... this sounds odd. will look into this

**Comment by JSJBDEV** [comment]
do you get any console spam when you do this?

**Comment by MattiT555** [comment]
how to get an access to the console while being in a singleplayer world?

**Comment by JSJBDEV** [comment]
oh right, well Ill give it a go

**Comment by JSJBDEV** [comment]
Ive just tried in my development world and it appears to work fine, i shall try using the jar

**Comment by JSJBDEV** [comment]
yup. its not working on the built jar 🤦

**Comment by MattiT555** [comment]
Okay, looked into the log and there are some errors which mention elements from your [mod,[](url)](url
[latest.log](https://github.com/JSJBDEV/PlatosTransporters/files/5011225/latest.log)
)

**Comment by MattiT555** [comment]
Oh, so it's just a general issue with your mod, not with my setup. Good for me, bad for you.

**Comment by JSJBDEV** [comment]
yup and I may have just found and its highly stupid

**Comment by JSJBDEV** [comment]
oh and I think I know why it works in my dev environment 🤦

**Comment by MattiT555** [comment]
Great that you have found it!

**Comment by JSJBDEV** [comment]
found it, I removed  leftover config operation from when the ships used to use radius, it stopped the ship being built because it doesnt exist and tries to parse it from config

**Comment by JSJBDEV** [comment]
uploading to cf now

**Comment by MattiT555** [comment]
So this issue thread deserves to be closed I guess. Thanks for such a quick response <3

**Comment by JSJBDEV** [comment]
i will close it once it gets approved on cf :D

**Comment by JSJBDEV** [comment]
see new version on CF! thanks for the report
